name: catbreeds
description: "A new Cat project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_native_splash: ^2.4.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/cat_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/cat_icon.png"
    background_color: "#ffffff"
    theme_color: "#6429cd"
  windows:
    generate: true
    image_path: "assets/images/cat_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/cat_icon.png"

flutter_native_splash:
  color: "#6429cd"
  image: assets/images/title.png
  branding: assets/images/cat_icon.png
  branding_mode: bottom
  android_12:
    color: "#6429cd"
    image: assets/images/title.png
    branding: assets/images/cat_icon.png
    branding_mode: bottom

flutter:
  uses-material-design: true

  assets:
    - assets/images/cat_load.gif
    - assets/images/cat_icon.png
    - assets/images/title.png

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu_regular.ttf
        - asset: assets/fonts/ubuntu_bold.ttf
